version: "3.9"

services: 

    employees-api:
        build: 
            context: .
            dockerfile: UtilityInspect.EmployeeService/Dockerfile
        environment: 
            - "EmployeeDatabaseSettings:ConnectionString=mongodb://microservice-db:27017"
        ports: 
            - "8081:80"
        depends_on: 
            - microservice-db

    fieldorder-api:
        build:
            context: .
            dockerfile: UtilityInspect.FieldOrderService/Dockerfile
        environment: 
            - "FieldOrderDatabaseSettings:ConnectionString=mongodb://microservice-db:27017"
        ports: 
            - "8082:80"
        depends_on: 
            - microservice-db
            

    microservice-db:
        image: mongo
        restart: always
        ports: 
            - "27017:27017"
        volumes: 
            - "microservice_db:/data/db"

        

volumes: 
    microservice_db: